src/components/kftray.tsx, src/components/portforward.tsx
I have separated portforward component
=> feat: separate portforward item component

src/components/add-config.tsx, src/components/kftray.tsx
moved new config modal to a separated component
=> feat: split add new config as a component

src/components/footer.tsx, src/components/kftray.tsx
=> feat: separate footer

src/components/kftray.tsx, src/components/portforward-table.tsx
=> feat: separate table

.eslintrc.cjs, dist/index.html, src-tauri/src/main.rs, src-tauri/utils/kubeforward/src/port_forward.rs, src/components/AddConfigModal/index.tsx, src/components/Header/index.tsx, src/components/KFtray/index.tsx, src/components/PortForwardRow/index.tsx, src/components/PortForwardTable/index.tsx, src/types/index.ts
=> feat: add port forward for specific configs

src/components/PortForwardRow/index.tsx
feat: disable switch when the function is running
=> feat: disable switch when the function is running

src-tauri/utils/kubeforward/src/proxy.rs
fix: convert username to lowercase
=> fix: convert username to lowercase

src/components/PortForwardTable/index.tsx
=> feat: prepare new version

README.md, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/tauri.conf.json
[fix: bug to open app in linux and add global shortcut](https://github.com/hcavarsan/kftray/commit/a064c30ed19fe8fe225e9a5527e45578c5c623a3)
=> fix: bug to open app in linux and add global shortcut

package.json, pnpm-lock.yaml, src-tauri/Cargo.lock, src-tauri/Cargo.toml
=> chore: update deps

dist/index.html, src-tauri/src/config.rs, src-tauri/src/main.rs, src/components/KFtray/index.tsx, src/components/PortForwardRow/index.tsx, src/components/PortForwardTable/index.tsx, src/types/index.ts
feat: add new button to delete multiples configs
=> feat: add new button to delete multiples configs

kftray-server/Dockerfile, kftray-server/src/http_proxy.rs
feat(server): docker image reduce size
=> feat(server): docker image reduce size

kftray-server/Cargo.lock, kftray-server/Cargo.toml, kftray-server/src/http_proxy.rs, kftray-server/src/tcp_proxy.rs
feat: add initial tests in server code
=> feat: add initial tests in server code

README.md, dist/index.html, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/keychain.rs, src-tauri/src/main.rs, src-tauri/tauri.conf.json, src/components/KFtray/index.tsx, src/components/Menu/index.tsx, src/components/PortForwardRow/index.tsx, src/components/PortForwardTable/index.tsx, src/components/SettingsModal/index.tsx, src/components/SyncConfigsButton/index.tsx, src/types/index.ts
- Synchronization of all port forwarding configurations with a GitHub repository.
- Users can now share their configurations easily with other users by setting up Git synchronization.
- The new "Configure Git Sync" menu option allows users to fill in their GitHub repository information.
- New "Sync Settings" button to apply synchronization settings immediately.
- "Synchronize Configurations" option added to the main screen for updating to the latest configurations from the configured repository.
- Encrypted storage of confidential information like the API key using the local operating system's keyring mechanisms:
- Keychain for macOS users.
- Credential Manager for Windows users.
- Secret Service for Linux users.
closes https://github.com/hcavarsan/kftray/issues/108
=> feat: create new mode to enable state sync with github repositories

src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/keychain.rs, src-tauri/src/logging.rs, src-tauri/src/main.rs
=> chore: revert fix conflicts

src/components/PortForwardTable/index.tsx
added useRef to avoid useeffect loop and webview high cpu usage
ref: https://github.com/hcavarsan/kftray/issues/137
=> fix: useeffect loop with high cpu usage

README.md
*Provide a brief description of the changes you have made and the issue if applicable.*
-  just fix some components versions in readme
- [ x I have tested the changes (if applicable).
- [ x I have updated the documentation (if applicable).
- [ x My changes do not break any existing functionalities.
*If you made UI changes, please include screenshots here.*
*Add any other context or information here.*
=> fix: versions in readme

kftray-server/src/http_proxy.rs, kftray-server/src/main.rs, kftray-server/src/tcp_proxy.rs, src-tauri/src/commands.rs, src-tauri/src/config.rs, src-tauri/src/remote_config.rs
fix: increase relay buffer size
note: temp changing tcp proxy to use http relay
=> fix: increase relay buffer size

kftray-server/src/main.rs
fix: resolve ip address before relay
=> fix: resolve ip address before relay

src/components/Menu/index.tsx, src/components/PortForwardTable/index.tsx, src/components/SyncConfigsButton/index.tsx
feat: improve menu footer layout
=> feat: improve menu footer layout

src/components/PortForwardRow/index.tsx
- **New Features**
- Introduced an icon button to open local URLs directly from the app for running configurations, enhancing user interaction and accessibility.
=> feat: add new icon to open local url

.github/workflows/ci.yaml, .github/workflows/main.yml, README.md, dist/index.html, kftray-server/Cargo.toml, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/commands.rs, src-tauri/src/main.rs, src-tauri/tauri.conf.json
fix: incorrect window position in linux when click in toggle button
ref: https://github.com/hcavarsan/kftray/issues/191
=> fix: incorrect window position in linux when click in toggle button

src/assets/theme.tsx, src/components/AddConfigModal/index.tsx, src/components/PortForwardSearchTable/index.tsx, src/components/PortForwardTable/index.tsx, src/components/SyncConfigsButton/index.tsx, src/types/index.ts
feat: improve frontend code and fix some lints
=> feat: improve frontend code and fix some lints

dist/index.html, src/assets/theme.tsx, src/components/CustomToast/CustomToast.tsx, src/components/CustomToast/index.tsx, src/components/KFtray/index.tsx, src/components/PortForwardRow/index.tsx, src/components/SettingsModal/index.tsx, src/components/SyncConfigsButton/index.tsx, src/types/index.ts
feat: improve error handling and create default toast component
=> feat: improve error handling and create default toast component

.github/workflows/main.yml, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs
fix: use enigo crate for linux mouse position and add arm linux build
=> fix: use enigo crate for linux mouse position and add arm linux build

.github/workflows/main.yml, README.md, dist/index.html, kftray-server/Cargo.lock, kftray-server/Cargo.toml, package.json, src-tauri/Cargo.lock, src-tauri/Cargo.toml, src-tauri/src/main.rs, src-tauri/tauri.conf.json
fix: use enigo crate for linux mouse position
=> fix: use enigo crate for linux mouse position

README.md
chore: improve Readme header logo and screenshot
=> chore: improve Readme header logo and screenshot

README.md
=> chore: improve readme layout

.github/workflows/main.yml, Cargo.lock, Cargo.toml, README.md, crates/kftray-server/Cargo.toml, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/src/main.rs, crates/kftray-tauri/src/tray.rs, crates/kftray-tauri/tauri.conf.json, frontend/dist/index.html, frontend/package.json, frontend/src/components/PortForwardTable/ContextsAccordion/PortForwardRow/index.tsx, frontend/src/components/PortForwardTable/ContextsAccordion/index.tsx
fix: menulist popover position and also the initial window position
=> fix: menulist popover position and also the initial window position

crates/kftray-tauri/src/window.rs
fix: don't close the app window when the position is invalid.
=> fix: don't close the app window when the position is invalid.

crates/kftray-tauri/src/main.rs, crates/kftray-tauri/src/tray.rs, crates/kftray-tauri/src/window.rs, frontend/src/components/Header/index.tsx
feat: add pin button to set always visible and focused
=> feat: add pin button to set always visible and focused

.github/workflows/ci.yaml
ci: only build image in ci workflow
=> ci: only build image in ci workflow

Cargo.lock, README.md, crates/kftray-server/Cargo.toml, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/src/commands.rs, crates/kftray-tauri/src/config.rs, crates/kftray-tauri/src/db.rs, crates/kftray-tauri/src/kubeforward/commands.rs, crates/kftray-tauri/src/kubeforward/kubecontext.rs, crates/kftray-tauri/src/kubeforward/logging.rs, crates/kftray-tauri/src/logging.rs, crates/kftray-tauri/src/main.rs, crates/kftray-tauri/src/models/kube.rs, crates/kftray-tauri/src/remote_config.rs, crates/kftray-tauri/src/utils/config_dir.rs, crates/kftray-tauri/src/utils/mod.rs, crates/kftray-tauri/src/utils/validate_configs.rs, crates/kftray-tauri/src/window.rs, crates/kftray-tauri/tauri.conf.json, frontend/package.json, frontend/src/components/PortForwardTable/ContextsAccordion/PortForwardRow/index.tsx
- **Config Directory Customization**:
- **Env Variables**: Now you can set your config directory with `KFTRAY_CONFIG` and `XDG_CONFIG_HOME` variables ( follow the [XDG spec](https://specifications.freedesktop.org/basedir-spec/latest/) ). 
- **Duplicate Config Alerts**:
- Added a check for multiple config directories. If we find more than one, you’ll get a warning with locations and how to fix it. No more guessing games!
=> feat: refactor configs dirs

.github/workflows/main.yml, crates/kftray-tauri/src/kubeforward/port_forward.rs, crates/kftray-tauri/src/utils/validate_configs.rs
fix: port forwarding stuck when http redirect to https
ref: https://github.com/hcavarsan/kftray/issues/266
=> fix: port forwarding stuck when http redirect to https

Cargo.lock, README.md, crates/kftray-commons/Cargo.toml, crates/kftray-portforward/src/core.rs, crates/kftray-server/Cargo.toml, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/tauri.conf.json, crates/kftui/Cargo.toml, crates/kftui/src/core/logging.rs, crates/kftui/src/core/port_forward.rs, crates/kftui/src/tui/app.rs, crates/kftui/src/tui/input/file_explorer.rs, crates/kftui/src/tui/input/mod.rs, crates/kftui/src/tui/ui/draw.rs, crates/kftui/src/tui/ui/popup.rs, crates/kftui/src/tui/ui/render.rs, crates/kftui/src/tui/ui/table.rs, crates/kftui/src/utils/config.rs, docs/kftray/INSTALL.md, examples/configs.json, frontend/package.json, hacks/kftray-utils/Cargo.lock, hacks/kftray-utils/Cargo.toml, hacks/kftray-utils/src/bump_version.rs, hacks/kftui_installer.sh
fix: kftui details not working properly
=> fix: kftui details not working properly

Cargo.lock, README.md, crates/kftray-commons/src/utils/config.rs, crates/kftray-server/Cargo.toml, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/tauri.conf.json, crates/kftui/Cargo.toml, docs/kftray/INSTALL.md, frontend/package.json
feat: export configs with pretty json
=> feat: export configs with pretty json

Cargo.lock, crates/kftray-portforward/Cargo.toml, crates/kftray-portforward/src/client.rs, crates/kftray-server/Cargo.toml, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/src/commands/kubecontext.rs, crates/kftray-tauri/tauri.conf.json, crates/kftui/Cargo.toml, docs/kftray/INSTALL.md, frontend/package.json, frontend/src/components/AddConfigModal/index.tsx, frontend/src/components/AddConfigModal/utils.ts, frontend/src/components/Main/index.tsx
feat:  improve kube client to handle more cases before fails
relates:
https://github.com/hcavarsan/kftray/issues/298
https://github.com/hcavarsan/kftray/issues/289
=> feat:  improve kube client to handle more cases before fails

Cargo.lock, crates/kftray-portforward/src/client.rs, crates/kftray-server/Cargo.toml, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/tauri.conf.json, crates/kftui/Cargo.toml, docs/kftray/INSTALL.md, frontend/package.json
[fix: eks auth failed](https://github.com/hcavarsan/kftray/commit/92b31c064040d6e321505d8c9df3ae08fe999fcc)
Ensure the Python client is used, and do not attempt to use Python inside the AppImage.
=> fix: eks auth failed

crates/kftray-commons/src/models/config_model.rs, crates/kftray-commons/src/utils/config.rs, frontend/src/components/AddConfigModal/index.tsx
feat: some minor improvements in add/import/export configs
=> feat: some minor improvements in add/import/export configs

.github/workflows/ci.yml, .github/workflows/main.yml, pnpm-lock.yaml
fix: add buildx setup in ci to have a multi-platform kftray container
relates: https://github.com/hcavarsan/kftray/issues/308
=> fix: add buildx setup in ci to have a multi-platform kftray container

Cargo.lock, crates/kftray-portforward/Cargo.toml, crates/kftray-portforward/src/client.rs, crates/kftray-tauri/Cargo.toml, crates/kftui/Cargo.toml
fix: test client with api version instead list namespace
=> fix: test client with api version instead list namespace

Cargo.lock, crates/kftray-commons/Cargo.toml, crates/kftray-commons/src/utils/config.rs
feat: if local_port is not set, get a random tcp unused port
relates: https://github.com/hcavarsan/kftray/issues/310
=> feat: if local_port is not set, get a random tcp unused port

crates/kftray-portforward/src/core.rs, crates/kftray-server/src/main.rs, crates/kftray-tauri/src/commands/kubecontext.rs, crates/kftui/src/main.rs, crates/kftui/src/tui/input/navigation.rs, frontend/src/components/AddConfigModal/index.tsx, frontend/src/components/AddConfigModal/utils.ts, frontend/src/components/AutoImportModal/index.tsx, frontend/src/types/index.ts
feat(frontend): improve AutoImportModal with kubeconfig support
=> feat(frontend): improve AutoImportModal with custom kubeconfig support

Cargo.lock, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/src/check.rs, crates/kftray-tauri/src/main.rs
feat(kftray-tauri): add check and manage ports to start port forward after app restart
relates: https://github.com/hcavarsan/kftray/issues/324
=> feat(kftray-tauri): add check and manage ports to start port forward after app restart

crates/kftray-commons/src/models/config_model.rs, crates/kftray-commons/src/utils/config.rs, crates/kftray-portforward/src/core.rs, crates/kftray-tauri/src/init_check.rs, crates/kftray-tauri/src/main.rs, crates/kftui/src/core/port_forward.rs, crates/kftui/src/tui/ui/table.rs, frontend/src/components/Main/index.tsx
perf(stop_all_port_forward): optimize stop_all_port_forward function
relates: https://github.com/hcavarsan/kftray/issues/324
=> perf(stop_all_port_forward): optimize stop_all_port_forward function

crates/kftray-tauri/src/commands/portforward.rs, crates/kftray-tauri/src/main.rs, crates/kftray-tauri/src/tray.rs, crates/kftray-tauri/tauri.conf.json, frontend/src/components/Header/index.tsx
feat: add close window button with port forward stop logic
relates: https://github.com/hcavarsan/kftray/issues/324
=> feat: add close window button with port forward stop logic

crates/kftray-tauri/src/commands/window_state.rs, crates/kftray-tauri/src/tray.rs, frontend/src/components/Header/index.tsx
feat: add pin window to systray menu
=> feat: add pin window to systray menu

.github/workflows/ci.yml, .github/workflows/main.yml
fix(ci): fix libwebkit2gtk version
=> fix(ci): fix libwebkit2gtk version

Cargo.lock, crates/kftray-commons/src/utils/db.rs, crates/kftray-portforward/Cargo.toml, crates/kftray-portforward/src/lib.rs, crates/kftray-portforward/src/network_utils.rs, crates/kftray-portforward/src/port_forward.rs, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/src/commands/github.rs, crates/kftui/Cargo.toml
fix(portforward): add loopback address configuration for non-primary addresses
relates: https://github.com/hcavarsan/kftray/issues/371
=> fix(portforward): add loopback address configuration for non-primary addresses

crates/kftray-portforward/src/hostsfile.rs, crates/kftray-portforward/src/kube/start.rs, crates/kftray-portforward/src/kube/stop.rs, crates/kftray-portforward/src/lib.rs
fixes issues with empty lines, missing entries, and file corruption during multiple parallel port-forward operations.
relates : https://github.com/hcavarsan/kftray/issues/372
=> fix(portforward): improve hosts file management for domain names

Cargo.lock, crates/kftray-commons/Cargo.toml, crates/kftray-portforward/Cargo.toml, crates/kftray-portforward/src/hostsfile.rs, crates/kftray-server/Cargo.toml, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/src/init_check.rs, crates/kftray-tauri/tauri.conf.json, crates/kftui/Cargo.toml, docs/kftray/INSTALL.md, frontend/package.json, package.json
improves application startup time by parallelizing port-forward operations and adding timeouts to prevent stalled connections.
this makes the startup process significantly faster when numerous port-forwards were previously running.
=> feat: improve startup for multiple port-forwards

.github/workflows/ci.yml, .github/workflows/main.yml
feat: update dependencies to use ubuntu 24.04 packages
=> feat: update dependencies to use ubuntu 24.04 packages

Cargo.lock, crates/kftray-portforward/Cargo.toml, crates/kftray-portforward/src/kube/client.rs, crates/kftray-portforward/src/kube/mod.rs, crates/kftray-portforward/src/kube/proxy.rs, crates/kftray-portforward/src/kube/start.rs, crates/kftray-portforward/src/kube/stop.rs, crates/kftray-portforward/src/kube/tests/mod.rs, crates/kftray-portforward/src/kube/tests/portforward_tests.rs
=> tests: add more tests

crates/kftray-tauri/src/commands/github.rs, crates/kftray-tauri/src/commands/httplogs.rs, crates/kftray-tauri/src/main.rs, crates/kftui/src/main.rs, crates/kftui/src/tests/test_file_explorer.rs, crates/kftui/src/tests/test_input.rs, crates/kftui/src/tests/test_navigation.rs, crates/kftui/src/tests/test_popup.rs, crates/kftui/src/tui/app.rs, crates/kftui/src/tui/input/file_explorer.rs, crates/kftui/src/tui/input/mod.rs, crates/kftui/src/tui/input/popup.rs, package.json
tests: add overall tests and code coverage
=> tests: add overall tests and code coverage

.github/workflows/ci.yml, .github/workflows/release.yml
set permissions and pin all actions versions to commit sha
=> ci: set permissions and pin all actions versions to commit sha

.github/workflows/ci.yml, .github/workflows/release.yml, .gitignore, .mise.toml, crates/kftray-commons/src/utils/config.rs, crates/kftray-http-logs/src/parser.rs, crates/kftray-portforward/src/hostfile_helper.rs, crates/kftray-portforward/src/hostsfile.rs, crates/kftray-portforward/src/kube/start.rs, crates/kftray-portforward/src/port_forward.rs, crates/kftray-tauri/src/commands/github.rs, crates/kftray-tauri/src/commands/helper.rs, crates/kftui/src/tests/test_draw.rs, crates/kftui/src/tui/ui/popup.rs, frontend/package.json, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, rust-toolchain.toml
fix: ci lints and another minor things
=> fix: ci lints and another minor things

.mise.toml, Cargo.lock, Cargo.toml, cliff.toml, crates/kftray-commons/Cargo.toml, crates/kftray-helper/Cargo.toml, crates/kftray-http-logs/Cargo.toml, crates/kftray-portforward/Cargo.toml, crates/kftray-server/Cargo.toml, crates/kftray-tauri/Cargo.toml, crates/kftui/Cargo.toml, crates/kftui/src/tui/input/file_explorer.rs, hacks/kftray-utils/Cargo.lock, hacks/kftray-utils/Cargo.toml, pnpm-lock.yaml, rust-toolchain.toml, rustfmt.toml
feat: remove unused deps and organize cargo workspace deps
=> feat: remove unused deps and organize cargo workspace deps

Cargo.lock, Cargo.toml, crates/kftray-network-monitor/Cargo.toml, crates/kftray-portforward/Cargo.toml, crates/kftray-tauri/Cargo.toml, crates/kftray-tauri/capabilities/migrated.json, crates/kftui/Cargo.toml
=> feat: remove unused deps

Cargo.lock, crates/kftui/src/tests/test_input.rs, crates/kftui/src/tui/input/mod.rs, crates/kftui/src/tui/ui/draw.rs, crates/kftui/src/tui/ui/render.rs
feat(kftui): add search bar to search configs in tables
ref: https://github.com/hcavarsan/kftray/issues/483
=> feat(kftui): add search bar to search configs in tables

crates/kftray-commons/src/models/window.rs, crates/kftray-tauri/src/commands/window_state.rs, crates/kftray-tauri/src/main.rs, crates/kftray-tauri/src/tray.rs, crates/kftray-tauri/src/window.rs
fix: wrong window position and size  in scaled monitor with high dpi
=> fix: wrong window position and size  in scaled monitor with high dpi
